# Your Discord bot token (Get one here: https://discord.com/developers/applications)
#botToken: MTA3MzYwNzg0NDI2NTQ3NjE1OA.GzgHqa.7SabnRmlkQtiprPrZ41VaDTi-cIUu_eiK3gP3A

# Developer bot token, you most likely don't need this
devBotToken: MTA5MDI5ODgyOTU5ODg5MjA2Mg.G9b7Tn.-o4way9rPia85RlQ1HfQN_YN5d9ybYvpO7cVUs

# Enables more verbose console outputs and logs in with the
# devBotToken instead of botToken
enableDev: true

ownerId: '844684172421496882'

apiKeys:
  # Steam API key used for the tf2 command
  # Details: (github link here)
  steam: B4094976715A7EAEE5C0C06565387102

  # Tenor API key used for the starboard script
  # Details: (github link here)
  tenor: LIVDSRZULELA

# Settings to control the bot's player behavior
player:
  # Should the bot leave the voice channel after the queue ends?
  leaveAfterQueueEnd: false
  autocomplete: true
